// `pm report` (spec §4.10, §8 milestone 10).

#include "commands/report.hpp"

#include <chrono>

#include "commands/common.hpp"
#include "core/events/analysis.hpp"
#include "core/events/crash_timeline.hpp"
#include "core/json/writer.hpp"
#include "core/render/event_view.hpp"
#include "core/text/format.hpp"
#include "core/version.hpp"
#include "platform/cpu_info.hpp"
#include "platform/os_info.hpp"
#include "platform/smbios.hpp"
#include "platform/cpu_topology.hpp"

namespace postmortem::commands {
namespace {

using text::to_hex;

// Spec §4.10: "--redact to strip hostname, usernames, serial numbers, and DIMM
// part numbers before sharing."
//
// Redaction replaces rather than deletes, so the report still reads correctly
// and the reader can see that something was removed rather than wondering
// whether the field was simply absent.
struct Redactor {
    bool enabled = false;

    [[nodiscard]] std::string operator()(const std::string& value,
                                         const char* what = "redacted") const {
        if (!enabled || value.empty()) return value;
        return std::string("[") + what + "]";
    }
};

std::string markdown_escape(const std::string& text) {
    std::string out;
    out.reserve(text.size());
    for (const char c : text) {
        if (c == '|') {
            out += "\\|";
        } else if (c == '\n') {
            out += ' ';
        } else {
            out += c;
        }
    }
    return out;
}

std::int64_t now_seconds() {
    return std::chrono::duration_cast<std::chrono::seconds>(
               std::chrono::system_clock::now().time_since_epoch())
        .count();
}

// Timestamps in the report are UTC throughout, not local: a report is written
// to be sent to someone else, and their local time is not the author's.
std::string build_markdown(const EventLoad& load, const events::Analysis& analysis,
                           const events::Timeline& timeline, const Redactor& redact) {
    const platform::CpuInfo cpu = platform::query_cpu_info();
    const platform::FirmwareInfo firmware = platform::query_firmware_info();
    const platform::OsInfo os = platform::query_os_info();

    std::string out;
    out += "# postmortem report\n\n";
    out += "Generated by postmortem " + std::string(kVersion) + " on " +
           text::format_utc(now_seconds()) + " from " + load.source + ".\n\n";

    out += "## Verdict\n\n";
    out += analysis.verdict + "\n\n";

    if (!analysis.findings.empty()) {
        out += "## Evidence\n\n";
        out += "| Confidence | Finding | Reasoning |\n|---|---|---|\n";
        for (const events::Finding& finding : analysis.findings) {
            out += "| " + std::string(events::confidence_text(finding.confidence)) + " | " +
                   markdown_escape(finding.claim) + " | " + markdown_escape(finding.reasoning) +
                   " |\n";
        }
        out += "\n";
    }

    out += "## System\n\n";
    out += "| Field | Value |\n|---|---|\n";
    out += "| CPU | " + markdown_escape(cpu.brand) + " |\n";
    out += "| Family/Model/Stepping | " + to_hex(cpu.signature.family, 2) + " / " +
           to_hex(cpu.signature.model, 2) + " / " + std::to_string(cpu.signature.stepping) +
           " |\n";
    out += "| Cores / threads | " + std::to_string(cpu.physical_cores) + " / " +
           std::to_string(cpu.logical_processors) + " |\n";
    if (cpu.microcode.has_value()) {
        out += "| Microcode | " + to_hex(cpu.microcode->revision, 8) + " |\n";
    }
    out += "| Board | " + markdown_escape(redact(firmware.board_manufacturer + " " +
                                                 firmware.board_product,
                                                 "board redacted")) + " |\n";
    out += "| BIOS | " + markdown_escape(firmware.bios_vendor) + " " +
           markdown_escape(firmware.bios_version) + " (" + firmware.bios_release_date + ") |\n";
    out += "| OS | " + markdown_escape(os.product_name) + " " + os.display_version + " build " +
           std::to_string(os.build) + "." + std::to_string(os.ubr) + " |\n";
    if (os.install_date.has_value()) {
        out += "| OS installed | " + text::format_utc(*os.install_date) + " |\n";
    }
    out += "\n";

    out += "## Incidents\n\n";
    if (load.incidents.empty()) {
        out += "No WHEA records in the selected range.\n\n";
    } else {
        out += "| # | When (UTC) | Severity | APIC IDs | Banks | Records |\n|---|---|---|---|---|---|\n";
        for (std::size_t i = 0; i < load.incidents.size(); ++i) {
            const events::Incident& incident = load.incidents[i];
            std::string apics;
            for (const unsigned apic : incident.apic_ids) {
                if (!apics.empty()) apics += ", ";
                apics += std::to_string(apic);
            }
            std::string banks;
            for (const unsigned bank : incident.banks) {
                if (!banks.empty()) banks += ", ";
                banks += std::to_string(bank);
            }
            const std::string severity =
                incident.uncorrected
                    ? (incident.context_corrupt ? "uncorrected, context corrupt" : "uncorrected")
                    : "corrected";
            out += "| " + std::to_string(i + 1) + " | " + text::format_utc(incident.time) +
                   " | " + severity + " | " + apics + " | " + banks + " | " +
                   std::to_string(incident.records.size()) + " |\n";
        }
        out += "\n";

        // Spec §4.10: "with the raw hex preserved so someone else can
        // re-verify the decode independently."
        out += "## Raw register values\n\n";
        out += "These are the values as logged, so the decode above can be checked "
               "independently.\n\n";
        out += "| Incident | APIC | Bank | MCA_STATUS | MCA_ADDR | MCA_MISC |\n"
               "|---|---|---|---|---|---|\n";
        for (std::size_t i = 0; i < load.incidents.size(); ++i) {
            for (const events::WheaRecord& record : load.incidents[i].records) {
                out += "| " + std::to_string(i + 1) + " | " +
                       (record.apic_id.has_value() ? std::to_string(*record.apic_id) : "-") +
                       " | " +
                       (record.mca_bank.has_value() ? std::to_string(*record.mca_bank) : "-") +
                       " | " +
                       (record.mci_stat.has_value() ? to_hex(*record.mci_stat, 16) : "-") +
                       " | " +
                       (record.mci_addr.has_value() ? to_hex(*record.mci_addr, 16) : "-") +
                       " | " +
                       (record.mci_misc.has_value() ? to_hex(*record.mci_misc, 16) : "-") +
                       " |\n";
            }
        }
        out += "\n";
    }

    if (!timeline.entries.empty()) {
        out += "## Timeline\n\n";
        out += timeline.headline + "\n\n";
        out += "| When (UTC) | Kind | What |\n|---|---|---|\n";
        for (const events::TimelineEntry& entry : timeline.entries) {
            out += "| " + text::format_utc(entry.time) + " | " +
                   std::string(events::kind_text(entry.kind)) + " | " +
                   markdown_escape(entry.summary) + " |\n";
        }
        out += "\n";
    }

    out += "## How to read the MCA decode\n\n";
    out += "`MCA_STATUS` bit 63 is Val, 62 Overflow, 61 UC (uncorrected), 60 Enabled, "
           "59 MiscV, 58 AddrV, 57 PCC (processor context corrupt). UC=1 together with PCC=1 "
           "is the important combination: it means the CPU could not continue and reset "
           "itself, which is why the crash left no bugcheck and no dump.\n\n";
    out += "Bits [15:0] hold the compound error code. `0x0108` decodes as "
           "`0000 0001 RRRR TTLL`, a memory hierarchy error, with RRRR=0 (generic), "
           "TT=10 (generic transaction) and LL=00 (level 0, i.e. the L1 cache).\n\n";
    out += "On AMD SMCA parts `MCA_ADDR` is not a flat address: bits [61:56] are an LSB field "
           "naming the least significant valid bit, and bits [55:0] are the address, which "
           "sign-extends from bit 47 into a canonical x86-64 address.\n\n";

    out += "---\n\n";
    out += "No kernel driver was used to produce this report. Every value comes from the "
           "Windows event log, SMBIOS, the registry and CPUID.\n";

    if (redact.enabled) {
        out += "\nThis report was generated with `--redact`: hostname, user names, serial "
               "numbers and part numbers have been replaced.\n";
    }

    return out;
}

}  // namespace

int run_report(const cli::CommandLine& cmdline, const text::Style& style) {
    (void)style;

    if (!cmdline.operands.empty()) {
        write_error("'report' takes no positional arguments; got '" + cmdline.operands.front() +
                    "'");
        return exit_code::kUsage;
    }

    std::string format = "md";
    if (const std::string* requested = cmdline.option("format")) format = *requested;
    if (cmdline.global.json) format = "json";
    if (format != "md" && format != "json" && format != "markdown") {
        write_error("unknown format '" + format + "'; expected json or md");
        return exit_code::kUsage;
    }

    Redactor redact;
    redact.enabled = cmdline.has_option("redact");

    LoadOptions options;
    options.all_providers = true;
    options.decode_records = true;
    const EventLoad load = load_events(cmdline, options);
    if (!load.ok) {
        write_error(load.error);
        return exit_code::kFailure;
    }

    events::AnalysisInput input;
    input.incidents = load.incidents;
    if (!cmdline.global.evtx.has_value()) {
        input.install_date = platform::query_os_info().install_date;
    }
    const events::Analysis analysis = events::analyse(input);
    const events::Timeline timeline = events::build_timeline(load.raw_events, load.incidents);

    if (format == "json") {
        const platform::CpuInfo cpu = platform::query_cpu_info();
        const platform::FirmwareInfo firmware = platform::query_firmware_info();
        const platform::OsInfo os = platform::query_os_info();

        json::Writer writer(true);
        writer.begin_object();

        // A stable schema, so reports can be diffed across time (spec §4.10).
        writer.key("report").begin_object();
        writer.member("schema", "postmortem/report");
        writer.member_int("schema_version", 1);
        writer.member("tool_version", kVersion);
        writer.member_int("generated_at_unix", now_seconds());
        writer.member("source", load.source);
        writer.member_bool("redacted", redact.enabled);
        writer.end_object();

        writer.key("system").begin_object();
        writer.member("cpu_brand", cpu.brand);
        writer.member("cpu_vendor", cpu::vendor_label(cpu.vendor));
        writer.member_uint("family", cpu.signature.family);
        writer.member_uint("model", cpu.signature.model);
        writer.member_uint("stepping", cpu.signature.stepping);
        writer.member_uint("physical_cores", cpu.physical_cores);
        writer.member_uint("logical_processors", cpu.logical_processors);
        if (cpu.microcode.has_value()) {
            writer.member_hex("microcode", cpu.microcode->revision, 8);
        } else {
            writer.member_null("microcode");
        }
        writer.member("board", redact(firmware.board_manufacturer + " " +
                                      firmware.board_product, "board redacted"));
        writer.member("bios_vendor", firmware.bios_vendor);
        writer.member("bios_version", firmware.bios_version);
        writer.member("bios_release_date", firmware.bios_release_date);
        writer.member("os_product", os.product_name);
        writer.member("os_display_version", os.display_version);
        writer.member_uint("os_build", os.build);
        writer.member_uint("os_ubr", os.ubr);
        if (os.install_date.has_value()) {
            writer.member_int("os_install_date_unix", *os.install_date);
        } else {
            writer.member_null("os_install_date_unix");
        }
        writer.end_object();

        writer.key("analysis").begin_object();
        writer.member("verdict", analysis.verdict);
        writer.member_uint("incident_count", analysis.incident_count);
        writer.member_uint("record_count", analysis.record_count);
        writer.member("rate_trend", events::rate_trend_text(analysis.trend));
        writer.key("findings").begin_array();
        for (const events::Finding& finding : analysis.findings) {
            writer.begin_object();
            writer.member("claim", finding.claim);
            writer.member("reasoning", finding.reasoning);
            writer.member("confidence", events::confidence_text(finding.confidence));
            writer.end_object();
        }
        writer.end_array();
        writer.end_object();

        writer.key("incidents").begin_array();
        for (const events::Incident& incident : load.incidents) {
            render::incident_json(incident, writer, true);
        }
        writer.end_array();

        writer.key("timeline").begin_array();
        for (const events::TimelineEntry& entry : timeline.entries) {
            writer.begin_object();
            writer.member_int("time_unix", entry.time);
            writer.member("time_utc", text::format_utc(entry.time));
            writer.member("kind", events::kind_text(entry.kind));
            writer.member("provider", entry.provider);
            writer.member_uint("event_id", entry.event_id);
            writer.member("summary", entry.summary);
            writer.end_object();
        }
        writer.end_array();

        writer.end_object();
        write_out(writer.take() + "\n");
        return exit_code::kSuccess;
    }

    write_out(build_markdown(load, analysis, timeline, redact));
    return exit_code::kSuccess;
}

}  // namespace postmortem::commands
